[SQUASH] drivers: Import MTK OSS connectivity from OPLUS OSS
commit c4377618ee6fa79c48ad203df47887977cf7369e
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Sun Apr 28 10:00:46 2024 +0200

    a34x: defconfig: enable Built-In connectivity drivers

commit c6a1230d0cbc266d6da19e8aaddacdaa2330e0e0
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Thu Aug 1 20:54:32 2024 +0200

    drivers: connectivity: build everything in kernel image

commit 743b70fda846ab94797993786901313ec2769c41
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Sun Apr 28 10:44:15 2024 +0200

    drivers: mediatek: connectivity: fix duplcate symbol error

    ld.lld: error: duplicate symbol: hmac_sha256
    >>> defined at rpmb-mtk.c:211 (/home/federico/Projects/android_kernel_samsung_a34x/out/../drivers/char/rpmb/rpmb-mtk.c:211)
    >>>            drivers/char/rpmb/rpmb-mtk.o:(hmac_sha256) in archive built-in.a
    >>> defined at sha256.c:136 (/home/federico/Projects/android_kernel_samsung_a34x/out/../drivers/misc/mediatek/connectivity/wlan/core/gen4m/wpa_supp/src/crypto/sha256.c:136)

commit 39beb6878093c567f7ad224f49f8eb481021f4db
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Sun Apr 28 10:33:32 2024 +0200

    drivers: mediatek: connectivity: remove Samsung custom duplicate driver

    Already present in core/gen4m

commit 8a35cc9d64d45aae76781393980fbe278d69ec0a
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Sat Apr 27 23:38:33 2024 +0200

    drivers: mediatek: connectivity: Various changes

    connectivity: Add an option to build wlan driver in kernel

    connectivity: bt: Allow platform to be overridden when building inline

    connectivity: gen4m: Fix built-in config detection

    connectivity: bt: Don't define module init/exit if built-in to kernel

    connectivity: {connfem,gps}: Build modules into kernel

    connectivity: Remove autoconf checks

    drivers: misc/mediatek: connectivity: wlan-gen4m: Change logging levels

    drivers: misc/mtk: connectivity-wlan: Queue delayed work on power efficient wq

    connectivity: mtk-conninfra: Use g_evt_ctx pointer to avoid errors

commit fa203aafd1547b9e432292c3dd8e2db56b5b6136
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Thu Aug 1 20:47:54 2024 +0200

    drivers: mediatek: connectivity: Port modules for in-kernel building and cleanup

commit 163c51d8532762d1718d5626e4ccf9d387cedcab
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Thu Aug 1 19:59:02 2024 +0200

    drivers: mediatek: connectivity: import Samsung customizations from CXE2 package

commit 14db591a9dcc1dcfd56d5c4ae031dd51192c551a
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Thu Aug 1 19:57:05 2024 +0200

    drivers: mediatek: connectivity: import Samsung customizations from BWK2 package

commit 5b25f1d2239b75a8f64cfcdeff5544c42740e093
Author: Fede2782 <78815152+Fede2782@users.noreply.github.com>
Date:   Thu Aug 1 19:54:38 2024 +0200

    drivers: mediatek: connectivity: Import MTK OSS connectivity modules from OPLUS

    https://github.com/OnePlusOSS/android_kernel_modules_oneplus_mt6877/tree/oneplus/mt6877_s_12.1_ivan

Co-authored-by: Fede2782 <78815152+Fede2782@users.noreply.github.com>